# Google Colab 데이터 로드

In [ ]:
#Step 1.분석할 데이터가 저장된 파일을 불러와서 변수에 할당합니다.
from google.colab import files
myfile = files.upload()
import io
import pandas as pd
#pd.read_csv로 csv파일 불러오기
study = pd.read_csv(io.BytesIO(myfile['공부시간과시험점수2.csv']),
                       encoding='cp949')
study

Saving 공부시간과시험점수2.csv to 공부시간과시험점수2.csv

       이름  공부시간  학원수  과외여부  시험점수
0     이원재  15.0    5     1  89.0
1     맹승주  14.5    5     0  86.5
2     안미경  14.0    5     1  86.0
3     서진수  13.5    4     1  85.5
4     황경인  13.0    4     0  85.0
5     신운무  12.0    4     1  83.0
6      권율  12.0    3     1  85.0
7      강준  11.0    3     0  82.0
8    신사임당  11.0    3     0  83.0
9     문무왕  10.5    3     1  82.0
10    김지희  10.5    2     1  81.5
11    임기승  10.0    2     1  82.0
12    강감찬  10.0    2     0  81.0
13  광개토대왕   9.5    2     0  78.0
14    이세혁   9.3    2     1  77.4
15    전우치   9.0    2     0  77.0
16    이순신   9.0    1     0  76.0
17    정진교   8.5    1     1  75.5
18   계백장군   8.5    1     0  76.0
19    왕광환   8.4    1     1  75.5
20    홍길동   8.2    1     0  75.0
21    곽재우   8.0    1     1  74.5
22    김유신   7.5    1     0  74.0
23    이승우   7.5    1     1  73.5
24    일지매   7.0    1     0  73.0

# 로컬 데이터 로드

In [2]:
#컴퓨터에서 작업하려면 아래 코드의 주석을 제거하고 실행하면 됩니다
import pandas as pd
study = pd.read_csv('../../머신러닝실습용자료/공부시간과시험점수2.csv',encoding='cp949')
study

       이름  공부시간  학원수  과외여부  시험점수
0     이원재  15.0    5     1  89.0
1     맹승주  14.5    5     0  86.5
2     안미경  14.0    5     1  86.0
3     서진수  13.5    4     1  85.5
4     황경인  13.0    4     0  85.0
5     신운무  12.0    4     1  83.0
6      권율  12.0    3     1  85.0
7      강준  11.0    3     0  82.0
8    신사임당  11.0    3     0  83.0
9     문무왕  10.5    3     1  82.0
10    김지희  10.5    2     1  81.5
11    임기승  10.0    2     1  82.0
12    강감찬  10.0    2     0  81.0
13  광개토대왕   9.5    2     0  78.0
14    이세혁   9.3    2     1  77.4
15    전우치   9.0    2     0  77.0
16    이순신   9.0    1     0  76.0
17    정진교   8.5    1     1  75.5
18   계백장군   8.5    1     0  76.0
19    왕광환   8.4    1     1  75.5
20    홍길동   8.2    1     0  75.0
21    곽재우   8.0    1     1  74.5
22    김유신   7.5    1     0  74.0
23    이승우   7.5    1     1  73.5
24    일지매   7.0    1     0  73.0

# 공통 실습 코드

In [5]:
#Step 2: 훈련용 데이터셋과 테스트용 데이터셋 나누어서 분석
from sklearn.model_selection import train_test_split

# data, target 지정
# 다중회귀분석의 경우 data를 여러개 설정.
data = study[ ['공부시간','학원수','과외여부'] ]
target = study['시험점수']

# train, test 데이터 분리
훈련용_data , 테스트용_data , 훈련용_target , 테스트용_target = train_test_split(
    data , target , test_size=0.2 , random_state=40)

In [6]:
# 선형회귀분석 학습
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(훈련용_data, 훈련용_target)

# 13, 5, 0이라는 값을 넣어 예측
lr.predict([[13,5,0]])

c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([84.86657458])

In [4]:
# 테스트 데이터로 스코어 확인
lr.score(테스트용_data , 테스트용_target)

0.8967399286768529